CREATE DATABASE command_and_control_db;


CREATE TABLE session_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID VARCHAR(255) NOT NULL,
    SESSION_REMOTE_ADDRESS VARCHAR(255) NOT NULL,
    SESSION_LOCAL_ADDRESS VARCHAR(255) NOT NULL,
    SESSION_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SESSION_CLOSED_AT TIMESTAMP,
    OS_NAME VARCHAR(255),
    OS_VERSION VARCHAR(255),
    OS_ARCH VARCHAR(255),
    USERNAME VARCHAR(255),
    USER_HOME VARCHAR(255),
    USER_CURRENT_WORKING_DIR VARCHAR(255),
    USER_LANGUAGE VARCHAR(255)


);