CREATE DATABASE command_and_control_db;


CREATE TABLE session_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID VARCHAR(255) NOT NULL,
    SESSION_REMOTE_ADDRESS VARCHAR(255) NOT NULL,
    SESSION_LOCAL_ADDRESS VARCHAR(255) NOT NULL,
    SESSION_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SESSION_CLOSED_AT TIMESTAMP
);